[project]
name = "rivulet-cli"
version = "3.0.0"
description = "Download any video/audio you want from a simple URL âœ¨"
dependencies = [
	"rivulet",
    "typer",
    "rich",
]

[tool.uv.sources]
rivulet = { workspace = true }

[project.scripts]
rivu = "rivulet_cli:run"

[build-system]
requires = ["uv_build>=0.8.0,<0.9"]
build-backend = "uv_build"
