[project]
name = "remora-cli"
version = "3.0.0"
description = "Download any video/audio you want from a simple URL âœ¨"
dependencies = ["remora", "typer>=0.21.0", "rich>=14.0.0"]

[project.scripts]
remora = "remora_cli:run"

[build-system]
requires = ["uv_build>=0.9.26,<0.10.0"]
build-backend = "uv_build"
